
import './globals.css';
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { headers } from 'next/headers';
import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
})


export const metadata = {
  title: 'RealEstate App',
  description: 'Generated by create next app',
};

export default async function  RootLayout({ children }) {
  const headersList = await headers();
  const cspHeader = headersList.get('Content-Security-Policy');
  return (
    <ClerkProvider cspHeader={cspHeader}>
      <html lang='en'>
        <body
          className={`${roboto.className}`} 
        >
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
