
import './globals.css';
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';

import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
})


export const metadata = {
  title: 'RealEstate App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${roboto.className}`} 
        >
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
